### ISSUE TITLE
Library <print> not working!

### ISSUE THREAD

**Issue by Shadoware** [brechtsanders/winlibs_mingw#237]
std::print() is not working though C++ reference says gcc 14 and clang 18 should support it.
 
 https://en.cppreference.com/w/cpp/compiler_support

**Comment by brechtsanders** [comment]
Did you specify the C++ version needed to support the feature (e.g. `-std=c++23`)?

**Comment by Shadoware** [comment]
Yes I did.
It works in Compiler Explorer site. I'm not sure if the site uses the same version exactly.

**Comment by Shadoware** [comment]
This is the error message I've received.

F:\> g++ -std=c++23 teste.cpp -o teste.exe

E:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\UserName\AppData\Local\Temp\ccG1f5Fe.o:teste.cpp:(.text$_ZSt14vprint_unicodeP6_iobufSt17basic_string_viewIcSt11char_traitsIcEESt17basic_format_argsISt20basic_format_contextINSt8__format10_Sink_iterIcEEcEE[_ZSt14vprint_unicodeP6_iobufSt17basic_string_viewIcSt11char_traitsIcEESt17basic_format_argsISt20basic_format_contextINSt8__format10_Sink_iterIcEEcEE]+0x197): undefined reference to `std::__open_terminal(_iobuf*)'
E:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\UserName\AppData\Local\Temp\ccG1f5Fe.o:teste.cpp:(.text$_ZSt14vprint_unicodeP6_iobufSt17basic_string_viewIcSt11char_traitsIcEESt17basic_format_argsISt20basic_format_contextINSt8__format10_Sink_iterIcEEcEE[_ZSt14vprint_unicodeP6_iobufSt17basic_string_viewIcSt11char_traitsIcEESt17basic_format_argsISt20basic_format_contextINSt8__format10_Sink_iterIcEEcEE]+0x24d): undefined reference to `std::__write_to_terminal(void*, std::span<char, 18446744073709551615ull>)'
collect2.exe: error: ld returned 1 exit status

**Comment by sisyphus** [comment]
@Shadoware, I take it that you're teste.cpp looks like:
```
#include <print>
int main()
{
    std::println("hello world");
}
```
At least, for me (using winlibs gcc-14.2.0), that produces the same error message as you have reported.

According to https://www.modernescpp.com/index.php/c23-a-modularized-standard-library-stdprint-and-stdprintln/ the C++23 "Hello World program" looks like:
```
import std;
int main() {
    std::println("Hello World"); 
}
```
which also fails for me:
```
D:\C>g++ -std=c++23 -o try.exe try.cpp
try.cpp:1:1: error: 'import' does not name a type
    1 | import std;
      | ^~~~~~
try.cpp:1:1: note: C++20 'import' only available with '-fmodules-ts', which is not yet enabled with '-std=c++20'
try.cpp: In function 'int main()':
try.cpp:5:10: error: 'println' is not a member of 'std'
    5 |     std::println("Hello World");
      |          ^~~~~~~

D:\C>g++ -std=c++23 -o try.exe try.cpp
try.cpp:1:1: error: 'import' does not name a type
    1 | import std;
      | ^~~~~~
try.cpp:1:1: note: C++20 'import' only available with '-fmodules-ts', which is not yet enabled with '-std=c++20'
try.cpp: In function 'int main()':
try.cpp:5:10: error: 'println' is not a member of 'std'
    5 |     std::println("Hello World");
      | 
```
Are those errors telling me that this gcc-14.2.0 winlibs build is only at C++20 ?

**Comment by Shadoware** [comment]
@sisyphus 

 ```c
#include <print>
int main()
{
    std::println("hello world");
}
```

This code works correctly in compiler explorer using gcc 14.2.

**Comment by brechtsanders** [comment]
I tried this and it works.
The missing pieces were:
- include the required header with `#include <print>`
- specify the C++ standard with compiler flag `-std=c++23`
- enable experimental C++ functions by specifying linker flag `-lstdc++exp`

So the code looks like the one @sisyphus proposed above and the build command looks like this:
```
g++ -std=c++23 teste.cpp -o teste.exe -lstdc++exp
```

**Comment by Shadoware** [comment]
@brechtsanders 
Put that information on the winlibs.com page!

**Comment by brechtsanders** [comment]
For those kind of questions it's better to look https://stackoverflow.com/

This specific issue was already asked on there ([link](https://stackoverflow.com/questions/78452682/stdprintln-print-not-working-in-winlibs-mingw-gcc-14-1/78466486#78466486))

Do you think I should put a page with common issues and solutions on the https://winlibs.com/ page?

**Comment by Shadoware** [comment]
> Do you think I should put a page with common issues and solutions on the https://winlibs.com/ page?

I think it's a good idea. There's already a "known issues" section there, or put just a link to a dedicated issues page.
